### ISSUE TITLE
Unable to prepare setup for platform roborock.vacuum: Platform not found (Exception importing custom_components.roborock.vacuum)

### ISSUE THREAD

**Issue by BernieV1977** [humbertogontijo/homeassistant-roborock#3]
Thx for this component!!! Unfortunately I got an error when setup the integration. The credentials are correct (I got a message in the Roborock app that someone logged in from antoher device). These are the errors from the log.

Logger: homeassistant.setup
Source: setup.py:338
First occurred: 09:20:49 (1 occurrences)
Last logged: 09:20:49

Unable to prepare setup for platform roborock.vacuum: Platform not found (Exception importing custom_components.roborock.vacuum).

Logger: homeassistant.loader
Source: custom_components/roborock/vacuum.py:68
Integration: Roborock (documentation, issues)
First occurred: 09:20:49 (1 occurrences)
Last logged: 09:20:49

Unexpected exception importing platform custom_components.roborock.vacuum
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/dietpi_userdata/homeassistant/custom_components/roborock/vacuum.py", line 56, in <module>
    class RoborockVacuum(StateVacuumEntity):
  File "/mnt/dietpi_userdata/homeassistant/custom_components/roborock/vacuum.py", line 68, in RoborockVacuum
    def send(self, command: str, params: list[Any] | None = None):
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

Regards,
Bernd

**Comment by BernieV1977** [comment]
I have Python 3.9.9 with a Roborock S6MaxV. Tia!

**Comment by humbertogontijo** [comment]
Its probably fixed now

**Comment by follares** [comment]
Now entity:
vacuum.roborock_s6_maxv

**Comment by follares** [comment]
![Screenshot_20221209-172155](https://user-images.githubusercontent.com/70486063/206746550-00398964-2572-4bbc-8cf8-7e42278122f4.png)

**Comment by BernieV1977** [comment]
> Its probably fixed now

No, still no luck.

Logger: homeassistant.setup
Source: setup.py:338
First occurred: 14:29:18 (1 occurrences)
Last logged: 14:29:18

Unable to prepare setup for platform roborock.vacuum: Platform not found (Exception importing custom_components.roborock.vacuum).

Logger: homeassistant.loader
Source: custom_components/roborock/vacuum.py:120
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 14:29:18 (1 occurrences)
Last logged: 14:29:18

Unexpected exception importing platform custom_components.roborock.vacuum
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/site-packages/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/home/homeassistant/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/dietpi_userdata/homeassistant/custom_components/roborock/vacuum.py", line 55, in <module>
    class RoborockVacuum(StateVacuumEntity):
  File "/mnt/dietpi_userdata/homeassistant/custom_components/roborock/vacuum.py", line 120, in RoborockVacuum
    def state(self) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by BernieV1977** [comment]
> Could you check if its fixed now?

Now it is working 👍👍👍. Th,x a lot!
