### ISSUE TITLE
Race condition when connecting to mqtt

### ISSUE THREAD

**Issue by the-ress** [humbertogontijo/homeassistant-roborock#431]
## Version of the custom_component

`main`

## What vacuum are you using?
2x Roborock S7 MaxV

## Describe the bug
1. I add the Roborock integration and log in
2. Usually only one of the vacuums get added 

I investigated and it turns out `RoborockMqttClient.on_connect` can get called before `self._async_response(CONNECT_REQUEST_ID)` call adds the future in `self._waiting_queue` so the future never gets resolved and `_async_response` times out.

I plan to fix it and send a PR (unless someone else fixes it before I get around to it).

## Debug log

Note: I added extra line to log the actual exception (instead of just `Failing setting up device...`).

```text
2023-08-03 01:40:36.959 DEBUG (MainThread) [custom_components.roborock] Getting network for 6Lk[redacted]
2023-08-03 01:40:36.959 INFO (MainThread) [roborock.cloud_api] [Chungus] Connecting to mqtt
2023-08-03 01:40:37.026 DEBUG (MainThread) [roborock.cloud_api] [Chungus] Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=[redacted] properties=None
2023-08-03 01:40:37.026 INFO (MainThread) [roborock.cloud_api] [Chungus] Starting mqtt loop
2023-08-03 01:40:37.047 DEBUG (Thread-3 (_thread_main)) [roborock.cloud_api] [Chungus] Received CONNACK (0, Success) properties=[TopicAliasMaximum : 0, MaximumQoS : 1, RetainAvailable : 0, MaximumPacketSize : 65536, WildcardSubscriptionAvailable : 1, SubscriptionIdentifierAvailable : 1, SharedSubscriptionAvailable : 1]
2023-08-03 01:40:37.047 INFO (Thread-3 (_thread_main)) [roborock.cloud_api] [Chungus] Connected to mqtt mqtt-eu-4.roborock.com:8883
2023-08-03 01:40:37.047 DEBUG (Thread-3 (_thread_main)) [roborock.cloud_api] [Chungus] Sending SUBSCRIBE (d0, m1) [(b'rr/m/o/[redacted]/6Lk[redacted]', {QoS=0, noLocal=False, retainAsPublished=False, retainHandling=0})]
2023-08-03 01:40:37.047 INFO (Thread-3 (_thread_main)) [roborock.cloud_api] [Chungus] Subscribed to topic rr/m/o/[redacted]/6Lk[redacted]
2023-08-03 01:40:37.062 WARNING (MainThread) [asyncio] Executing <Task pending name='config entry setup [redacted] roborock [redacted]' coro=<ConfigEntry.async_setup() running at /home/vscode/.local/lib/python3.11/site-packages/homeassistant/config_entries.py:390> wait_for=<Future pending cb=[Task.task_wakeup()] created at /workspaces/homeassistant-roborock/roborock/roborock_future.py:14> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.11/asyncio/tasks.py:754] created at /usr/local/lib/python3.11/asyncio/tasks.py:374> took 0.110 seconds
2023-08-03 01:40:37.066 DEBUG (Thread-3 (_thread_main)) [roborock.cloud_api] [Chungus] Received SUBACK
2023-08-03 01:40:41.051 WARNING (MainThread) [custom_components.roborock] Failing setting up device 6Lk[redacted]
2023-08-03 01:40:41.057 ERROR (MainThread) [custom_components.roborock] id=0 Timeout after 4 seconds
Traceback (most recent call last):
  File "/workspaces/homeassistant-roborock/custom_components/roborock/__init__.py", line 116, in async_setup_entry
    networking = await map_client.get_networking()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/homeassistant-roborock/roborock/api.py", line 482, in get_networking
    return await self.send_command(RoborockCommand.GET_NETWORK_INFO, return_type=NetworkInfo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/homeassistant-roborock/roborock/api.py", line 382, in send_command
    response = await self._send_command(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/homeassistant-roborock/roborock/cloud_api.py", line 191, in _send_command
    return await self.send_message(roborock_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/homeassistant-roborock/roborock/cloud_api.py", line 155, in send_message
    await self.validate_connection()
  File "/workspaces/homeassistant-roborock/roborock/api.py", line 310, in validate_connection
    await self.async_connect()
  File "/workspaces/homeassistant-roborock/roborock/cloud_api.py", line 145, in async_connect
    (_, err) = await self._async_response(CONNECT_REQUEST_ID)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/homeassistant-roborock/roborock/api.py", line 321, in _async_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=0 Timeout after 4 seconds
2023-08-03 01:40:41.105 DEBUG (MainThread) [custom_components.roborock] Getting network for 1Qa[redacted]
2023-08-03 01:40:41.105 INFO (MainThread) [roborock.cloud_api] [Fungus] Connecting to mqtt
2023-08-03 01:40:41.164 DEBUG (MainThread) [roborock.cloud_api] [Fungus] Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=[redacted] properties=None
2023-08-03 01:40:41.165 INFO (MainThread) [roborock.cloud_api] [Fungus] Starting mqtt loop
2023-08-03 01:40:41.187 DEBUG (Thread-4 (_thread_main)) [roborock.cloud_api] [Fungus] Received CONNACK (0, Success) properties=[TopicAliasMaximum : 0, MaximumQoS : 1, RetainAvailable : 0, MaximumPacketSize : 65536, WildcardSubscriptionAvailable : 1, SubscriptionIdentifierAvailable : 1, SharedSubscriptionAvailable : 1]
2023-08-03 01:40:41.188 INFO (Thread-4 (_thread_main)) [roborock.cloud_api] [Fungus] Connected to mqtt mqtt-eu-4.roborock.com:8883
2023-08-03 01:40:41.188 DEBUG (Thread-4 (_thread_main)) [roborock.cloud_api] [Fungus] Sending SUBSCRIBE (d0, m1) [(b'rr/m/o/[redacted]/1Qa[redacted]', {QoS=0, noLocal=False, retainAsPublished=False, retainHandling=0})]
2023-08-03 01:40:41.189 INFO (Thread-4 (_thread_main)) [roborock.cloud_api] [Fungus] Subscribed to topic rr/m/o/[redacted]/1Qa[redacted]
2023-08-03 01:40:41.202 WARNING (MainThread) [asyncio] Executing <Task cancelling name='config entry setup [redacted] roborock [redacted]' coro=<ConfigEntry.async_setup() running at /home/vscode/.local/lib/python3.11/site-packages/homeassistant/config_entries.py:390> wait_for=<Future pending cb=[Task.task_wakeup()] created at /workspaces/homeassistant-roborock/roborock/roborock_future.py:14> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.11/asyncio/tasks.py:754] created at /usr/local/lib/python3.11/asyncio/tasks.py:374> took 0.150 seconds
2023-08-03 01:40:41.213 DEBUG (MainThread) [roborock.cloud_api] [Fungus] id=11316 Requesting method get_network_info with []
2023-08-03 01:40:41.213 DEBUG (MainThread) [roborock.cloud_api] [Fungus] Sending PUBLISH (d0, q0, r0, m2), 'b'rr/m/i/[redacted]/1Qa[redacted]'', properties=None, ... (215 bytes)
2023-08-03 01:40:41.220 DEBUG (Thread-4 (_thread_main)) [roborock.cloud_api] [Fungus] Received SUBACK
2023-08-03 01:40:41.281 DEBUG (Thread-4 (_thread_main)) [roborock.cloud_api] [Fungus] Received PUBLISH (d0, q0, r0, m0), 'rr/m/o/[redacted]/1Qa[redacted]', properties=[], ...  (215 bytes)
2023-08-03 01:40:41.300 DEBUG (MainThread) [roborock.cloud_api] [Fungus] id=11316 Response from get_network_info: [redacted]
```

**Comment by humbertogontijo** [comment]
Oh, good job! Thank you for your contribution to the repository

**Comment by Lash-L** [comment]
Great find! I look forward to your PR

**Comment by humbertogontijo** [comment]
Try out 1.0.10
Hope it is fixed

**Comment by the-ress** [comment]
I haven’t tested it on my devcontainer yet (that’s where I had the issue), but from the code it looks it should work.

But it’s logging warnings now:
```
/usr/local/lib/python3.11/site-packages/roborock/api.py:312: RuntimeWarning: coroutine 'RoborockClient._async_response' was never awaited await self.async_connect()
```

**Comment by humbertogontijo** [comment]
Yeah. Will be fixed after updating the library
https://github.com/humbertogontijo/python-roborock/commit/da83078f7ef8f333fa46b75603ce8a88bb97914d

**Comment by the-ress** [comment]
It still not quite right (it's logging errors). I created a PR to fix that: humbertogontijo/python-roborock#103
